install.packages("sp")
library(sp)
library(ggplot2)
AFG_adm1 <- readRDS("gadm36_AFG_1_sp.rds")
op <- par(mar=c(0,0,0,0))
plot(AFG_adm1)
AFG_adm1$NAME_1
install.packages("plotrix")
library(plotrix) 
install.packages("ggtree")
devtools::install_github("GuangchuangYu/ggtree")
install.packages("maps")
library(ggtree)
install.packages("pipeR")
install.packages("grid")
install.packages("XML")
install.packages("gtable")
p_load(pipeR,grid,XML,gtable)
library(pipeR);library(grid);library(XML);library(gtable);
head(AFG_adm1)
