---
title: "run expectancy matrix"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#load libraries and source for retrosheets 
```{r}
library(Lahman)
library(devtools)
library(plyr)
library(tidyverse)
```

```{r}
#create the all 2020 play by play Team file
cwevent <- function(year) {
  if (identical(Sys.which("cwevent"), "")) {
    stop("Please download and install the chadwick utility:\n",
         "http://chadwick.sourceforge.net/doc/index.html")
  }
  # do everything in a temporary directory
  owd <- getwd()
  on.exit(setwd(owd))
  tmp <- tempdir()
  setwd(tmp)
  
  # obtain the scripts for a particular year
  zipfile <- paste0(year, "eve.zip")
  download.file(
    url = sprintf("http://www.retrosheet.org/events/%seve.zip", year),
    zipfile
  )
  unzip(zipfile)
  
  # run the scripts
  argz <- c("-y", year, "-f", "0-96", "-x", "0-62",
            paste0(year, "*.EV*"))
  te <- system2("cwevent", args = argz, stdout = TRUE)
  df <- read.csv(
    text = paste(te, collapse = "\n"),
    header = FALSE,
    stringsAsFactors = FALSE
  )
  # add proper field names and an event descriptor
  e <- environment()
  data(fields, package = "chadwick", envir = e)
  data(event_codes, package = "chadwick", envir = e)
  nms <- c(fields$standard$Header, fields$extended$Header)
  df <- setNames(df, nms)
  df <- cbind(df, Year = as.integer(year))
  dplyr::left_join(df, event_codes, by = "EVENT_CD")
}
df <- cwevent(2020)
```
```{r}
#Set up the run expectancy matrix for the 2020 MLB Season
#Define runs scored in the remainder of the inning 
#Total Runs Scored every game fo 2020 regualr season
df$RUNS <- with(df, AWAY_SCORE_CT + HOME_SCORE_CT)
# add half inning variable with game numbeer, inning number, and the team at bat
df$HALF.INNING <- with(df,  paste(GAME_ID, INN_CT, BAT_HOME_ID))
#Total Runs Scored in each half inning
df$RUNS.SCORED <- with(df, (BAT_DEST_ID > 3) +  (RUN1_DEST_ID > 3) + 
                               (RUN2_DEST_ID > 3) + (RUN3_DEST_ID > 3)) 
#put total runs scored and number of half innings ain data frame RUNS.SCORED.INNING
RUNS.SCORED.INNING <- aggregate(df$RUNS.SCORED,  list(HALF.INNING=df$HALF.INNING), sum)
#Total Runs Scored at the beginning of a half inning
RUNS.SCORED.START <- aggregate(df$RUNS,  list(HALF.INNING=df$HALF.INNING), "[", 1) 

#get max runs scored for half innings which is hte sum of runs scored plus initial runs scored
MAX <- data.frame(HALF.INNING=RUNS.SCORED.START$HALF.INNING) 
MAX$x <- RUNS.SCORED.INNING$x + RUNS.SCORED.START$x 
# merge with 2020 data frame and create new variable MAX.RUNS
df <- merge(df, MAX) 
N <- ncol(df) 
names(df)[N] <- "MAX.RUNS"  

#Define total runs scored in remainder of hte inning(bottom of inning) as max runs scored - runs 
df$RUNS.ROI <- with(df, MAX.RUNS - RUNS) 
# Create 3 binary varaibles of the base runner on first,second, or third. 1 if on base. zero if base empty. as well as the code for the runner on base
RUNNER1 <- ifelse(as.character(df[ ,"BASE1_RUN_ID"]) =="", 0, 1)  
RUNNER2 <- ifelse(as.character(df[ ,"BASE2_RUN_ID"]) =="", 0, 1)  
RUNNER3 <- ifelse(as.character(df[ ,"BASE3_RUN_ID"]) =="", 0, 1) 
# create a state function that puts the info of people on base and the amount of outs 
get.state <- function(runner1, runner2, runner3, outs) { 
  runners <- paste(runner1, runner2, runner3, sep="")
  paste(runners, outs) 
  } 
df$STATE <- get.state(RUNNER1, RUNNER2, RUNNER3, df$OUTS_CT) 
# Create 3 new variables based on the number of baserunners after each play in the half inning
NRUNNER1 <- with(df, as.numeric(RUN1_DEST_ID == 1 |  BAT_DEST_ID == 1)) 
NRUNNER2 <- with(df, as.numeric(RUN1_DEST_ID == 2 |  RUN2_DEST_ID == 2 | BAT_DEST_ID==2)) 
NRUNNER3 <- with(df, as.numeric(RUN1_DEST_ID == 3 |  RUN2_DEST_ID == 3 | RUN3_DEST_ID == 3 | BAT_DEST_ID == 3))
# new outs variable to show number of outs after each play in half inning
NOUTS <- with(df, OUTS_CT + EVENT_OUTS_CT)  
df$NEW.STATE <- get.state(NRUNNER1, NRUNNER2, NRUNNER3, NOUTS) 
# use the subset function on data frame df that indicates a change in STATE when a run has scored
df <- subset(df, (STATE != NEW.STATE) | (RUNS.SCORED > 0)) 

data.outs <- ddply(df, .(HALF.INNING), summarize,  Outs.Inning=sum(EVENT_OUTS_CT))  
df <- merge(df, data.outs)  
dfC <- subset(df, Outs.Inning == 3) 
RUNS <- with(dfC, aggregate(RUNS.ROI, list(STATE), mean)) 
RUNS$Outs <- substr(RUNS$Group, 5, 5) 
RUNS <- RUNS[order(RUNS$Outs),] 



RUNS.out <-matrix(round(RUNS$x, 2), 8, 3) 
dimnames(RUNS.out)[[2]] <- c("0 outs", "1 out", "2 outs")  
dimnames(RUNS.out)[[1]] <- c("000", "001", "010", "011", "100", "101",  "110", "111")  
```

```{r}
#Run Expectancy Function
runs.expectancy <- function(data){
  RUNS <- with(data, aggregate(RUNS.ROI, list(STATE), mean))
  RUNS$Outs <- substr(RUNS$Group, 5, 5)
  RUNS <- RUNS[order(RUNS$Outs), ]  
  RUNS.out <- matrix(round(RUNS$x, 2), 8, 3)
  dimnames(RUNS.out)[[2]] <- c("0 outs", "1 out", "2 outs")
  dimnames(RUNS.out)[[1]] <- c("000", "001", "010", 
                               "011", "100", "101", "110", "111")
  RUNS.out
}
#output run expectancy for all 24 base and out scenarios in a half inning
runs.expectancy(df)
```

